version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn build
            - run: yarn test
      - store_test_results:
          path: test-results
  publish_npm:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/project/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - publish_npm:
          requires:
            - build-and-test
